language: php

matrix:
  include:
    - php: 5.5
      env:
        - REDIS_HOST=127.0.0.1
    - php: 5.6
      env:
        - REDIS_HOST=127.0.0.1
    - php: 7.0
      env:
        - REDIS_HOST=127.0.0.1

services:
  - redis-server

before_install: 
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer selfupdate

install:
  - composer install

script:
  - php console/cache-console.php code-coverage:generate
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml