language: php

matrix:
  include:
    - php: 7.1
      env:
        - REDIS_HOST=127.0.0.1
    - php: 7.2
      env:
        - REDIS_HOST=127.0.0.1

services:
  - redis-server

before_install: 
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer selfupdate

install:
  - composer install

script:
  - bin/cache tests:run
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml